#!/bin/sh /etc/rc.common

START=50
STOP=90
USE_PROCD=1

start_service() {
        [ -s /etc/snode.c/mqttbridge.conf ] || return 0
        procd_open_instance
        procd_set_param command /usr/bin/mqttbridge --daemonize=false --quiet=false --enforce-log-file=false
        procd_append_param command bridge --html-dir /usr/var/www/mqttsuite/mqttbridge
        procd_set_param stdout 1
        procd_set_param stderr 1
        procd_set_param respawn
        procd_close_instance
}
