function(make_includable INPUT_FILE OUTPUT_FILE)
    file(READ ${INPUT_FILE} CONTENT)
    string(REGEX REPLACE "[ \t\r\n]" "" CONTENT "${CONTENT}")
    set(CONTENT "static std::string mappingJsonSchemaString = R\"(${CONTENT})\";\n")
    file(WRITE ${OUTPUT_FILE} "${CONTENT}")
endfunction(make_includable)

if(mapping-schema.json IS_NEWER_THAN ${TARGET_PATH}/mapping-schema.json.h)
    make_includable(mapping-schema.json ${TARGET_PATH}/mapping-schema.json.h)
endif(mapping-schema.json IS_NEWER_THAN ${TARGET_PATH}/mapping-schema.json.h)
